name: 'Paper & Twig'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11841
title: 'Paper & Twig - by Carla'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#897e77'
    - '#fded6f'
    - '#d1c779'
    - '#a09792'
  brandStrength: 0.5625
  lightness: 0.9375
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
