name: 'Paper & Twig'
favicon: null
layout_spectrum: 0.6278158533386886
typography_spectrum: 0.16273217275738716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5526268039830029
  lightness: 0.9300134098157287
  saturation: 0.18907108646817505
  rhythmicContrast: 0.886842358391732
purpose: []
